[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['cd backend && echo "Build phase completed - Prisma will run at startup"']

[start]
cmd = 'cd backend && npm start'